"""add Department

Revision ID: 658c8e1aea44
Revises: 7cea85355b49
Create Date: 2025-05-27 22:52:28.736389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658c8e1aea44'
down_revision = '7cea85355b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
